services:

  db:
    image: postgres:17.5-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres-data-chat:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data-chat:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

  broker:
    image: apache/kafka:3.9.1
    container_name: broker
    ports:
      - 9092:9092
    volumes:
      - kafka-data-chat:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - broker
    ports:
      - 9999:8080
    restart: always
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      KAFKA_CLUSTERS_0_JMXENABLED: false

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data-chat:/data
    environment:
      - REDIS_PASSWORD=changemeinprodtoo!

volumes:
  postgres-data-chat:
    driver: local
  keycloak-data-chat:
    driver: local
  kafka-data-chat:
    driver: local
  redis-data-chat:
    driver: local