logging:
  level:
    com.sobow: "debug"

server:
  port: 8082

spring:
  application:
    name: chat-realtime

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/chat-app"