logging:
  level:
    com.devtiro: "debug"

server:
  port: 8083

spring:
  application:
    name: chat-message
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/messages"
    username: postgres
    password: changemeinprod!

  flyway:
    # To prevent flyway loading migrations from other modules
    locations: classpath:db/migration/message
    url: jdbc:postgresql://localhost:5432/messages
    user: postgres
    password: changemeinprod!


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: chat-message
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.sobow.chat.common.domain.dto"
